### ISSUE TITLE
issue with running Omega - missing packages

### ISSUE THREAD

**Issue by clau-vasq** [royerlab/napari-chatgpt#2]
Hi! I followed the instructions to install into a new condo environment. I got stuck at the "solving environment" stage when I tried to  install napari from conda-forge, so instead I used `pip install "napari[all]"`. Downstream I used pip to install napari-chatgpt and when I tried to "start Omega" I got that I was missing the cryptography module. So I installed that and now I'm getting the following:
`dlopen(/opt/anaconda3/envs/napari-chatgpt/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 0x0002): Library not loaded: @rpath/libssl.1.1.dylib` 

Do you think this is an issue with the strategy I used to install napari? (I should try conda-forge again?) Or do you think something else might be going on?

**Comment by royerloic** [comment]
You would need to provide more information about the system you are using (operating system, type of machine, etc...) for troubleshooting this.

The cryptography is only needed when storing the key via the UI interface.
If you store your OpenAI key in the env variable: OPENAI_API_KEY then it just works,
and it will never need to encrypt or decrypt anything. I am pushing a version with local imports just in case.... 

hope this helps...

**Comment by royerloic** [comment]
Looking at this again, did you have success?
If you work on a mac M1 or M2, you must use conda and conda-forge,
and follow the instructions as provided in the readme...

Let me know how it went...

**Comment by royerloic** [comment]
Closing this issue as I assume this is solved now...
