### ISSUE TITLE
Can I reset my OpenAI password?

### ISSUE THREAD

**Issue by Eddymorphling** [royerlab/napari-chatgpt#21]
Hi, I cannot remember my OpenAI password that I use to start Omega. Can I reset this password or delete the .json file that stores this password? I even tried to install Omega on a new env but it keeps asking for the password rather than setting up a new OpenAI key. Any help would be appreciated! Thanks.

**Comment by royerloic** [comment]
That is a good idea, I will add this feature ASAP. 
In the meantime, you can remove the corresponding JSON file in folder '~\.omega_api_keys'.
This way it will ask again for the key and for a password.
