### ISSUE TITLE
Error when loading Napari-chatgpt: Importing PromptTemplate from langchain root module is no longer supported

### ISSUE THREAD

**Issue by cbudjan** [royerlab/napari-chatgpt#26]
When trying to load Napari-chatgpt from within Napari, I'm getting the following error:

Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.

A cursory search suggests that the import statement for the langchain package needs to be updated (at the plugin level).

**Comment by royerloic** [comment]
I am pushing a new version today that should resolve this issue. I will close this issue once you confirm that it works on your end.
