### ISSUE TITLE
installation issues in napari 4.18

### ISSUE THREAD

**Issue by danidean** [royerlab/napari-chatgpt#30]
Hi,

trying to install napari-chatgpt via the **install/uninstall plugin** option from napari ui, the following error accrues:

```
Could not solve for environment specs
The following package could not be installed
└─ napari-chatgpt does not exist (perhaps a typo or a missing channel).
```

I was able to install the chatgpt plugin in napari 4.19 release.

please assist.

thanks,

 - Dean

**Comment by royerloic** [comment]
Could you provide more details about your environment, and the exact command sequence that caused the issue? Without details and context it is very difficult to understand what happened. Also, did you try again, and does it still fail?

**Comment by royerloic** [comment]
Closing because this is related to an outdated version of napari
