### ISSUE TITLE
API key problem

### ISSUE THREAD

**Issue by jinxsfe** [royerlab/napari-chatgpt#43]
Hi, I install the chat-GPT OMEGA but I can not run it,
![image](https://github.com/royerlab/napari-chatgpt/assets/121477741/dbae50a8-51d2-4e41-a0cb-6cb6e4b2d372)
I had already create account for API key
![image](https://github.com/royerlab/napari-chatgpt/assets/121477741/94ca79a9-bc1d-4ba3-875a-77faa70811a9)
do I missing any steps?

**Comment by royerloic** [comment]
The most likely explanation is that there is an extra character appended to the key that you entered, 
or that for some reason the key was not entered correctly. 

I would make sure that:

1. You have the latest version of Omega installed
2. Clear the exiting API key
3. Enter the new key

Also, be careful to not confuse the API key from the password used to secure it!
You pick your own password, but the key is provided by OpenAI...

Hope this helps,
Please apply the steps above and let us know how it goes...

**Comment by royerloic** [comment]
I will assume this is resolved
