### ISSUE TITLE
iOS incompatible architecture

### ISSUE THREAD

**Issue by GesineMueller** [royerlab/napari-chatgpt#8]
Hi there,

I tried to install your plugin via pip, which worked (no error message), but can't run Napari now. When being in the active environment and try to open Napari via 'napari' I receive an error of an incompatible architecture (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')). I have a Mac iOS Ventura 13 with an M1 chip and have also installed the apple_wrapper: mamba install -c conda-forge ocl_icd_wrapper_apple. 

Anything I additionally have to install? 

Thanks!

**Comment by royerloic** [comment]
Hi Gesine,

I also have a M1 mac, so it should work fine.
Did you create a fresh conda/mamba install?
It is very important to follow the instructions,
especially on a M1/M2 mac...

Screenshots of errors and more details would help
understand the issue...

Hope this helps!

Loic

**Comment by royerloic** [comment]
Closing as I assume this has been solved now...
