### ISSUE TITLE
authentic failed for omega

### ISSUE THREAD

**Issue by jinxsfe** [royerlab/napari-chatgpt#9]
<img width="1105" alt="Screenshot 2023-05-25 at 10 04 41 PM" src="https://github.com/royerlab/napari-chatgpt/assets/121477741/2334deea-d1ba-48ac-81ca-6614a91fc148">
 my question is I had already have log in to Omega and segmentation successfully , but after that I had uninstalled packages and reinstalled Oemga, at this time, I delete the original key and set the new key

<img width="579" alt="Screenshot 2023-05-25 at 10 19 31 PM" src="https://github.com/royerlab/napari-chatgpt/assets/121477741/79247c6d-f6b2-47ba-babd-72792e936715">
it directly tell me to enter password , do not insert the openai key
<img width="159" alt="Screenshot 2023-05-25 at 10 20 16 PM" src="https://github.com/royerlab/napari-chatgpt/assets/121477741/04218510-f6f8-4c0c-bce0-947b56b6b6d7">
the openai key I write like that, but is also failed, why?

**Comment by royerloic** [comment]
Dear jinxsfe,

Thanks for your interest in Omega, 
I must say I do not fully understand your question.

Let me re-explain how the 'Key Vault' works:

1- The first time you open Omega, you eventually get greeted
by a Key Vault popup that asks you for two things: the OpenAI API **key**
and a **password** of your choice to secure that key. Once this step is completed,
you do not need to enter the OpenAI key (ever) again. 

2- Next time you use Omega, you only need to enter your chosen password 
(not the OpenAI API KEY!). So pick a password you can remember... 

You seem to mention some installation and de-installation; not sure exactly what happened
there, but starting from a fresh conda environment might be a good idea...

Alternatively to the approach above, you can also set your OpenAI key at the system
level using an env variable. Follow these instructions:  
https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

Hope this helps!
Don't hesitate to ask follow-up questions 
in the eventuality that I misunderstood the nature of your question(s).

**Comment by royerloic** [comment]
I just pushed an update that should help with OpenAI API key issues.

**Comment by royerloic** [comment]
Closing this issue as I assume this has been solved...
